// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBObmOHkUzGeK9KLaMtqCQM8TLFPjvxqFQ',
    appId: '1:322364170094:web:09fb9bc07236d1b8c5ab7f',
    messagingSenderId: '322364170094',
    projectId: 'absen-8d396',
    authDomain: 'absen-8d396.firebaseapp.com',
    databaseURL: 'https://absen-8d396-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'absen-8d396.appspot.com',
    measurementId: 'G-R4HNNMWNWL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEgkydZWFomi3Jb_3aLQnScYZLrciVyis',
    appId: '1:322364170094:android:41acbd5a6b48150ec5ab7f',
    messagingSenderId: '322364170094',
    projectId: 'absen-8d396',
    databaseURL: 'https://absen-8d396-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'absen-8d396.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjJTqaVRrxrjIuhHiFqwi4ju-i16esahE',
    appId: '1:322364170094:ios:0536fd01d2a9513bc5ab7f',
    messagingSenderId: '322364170094',
    projectId: 'absen-8d396',
    databaseURL: 'https://absen-8d396-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'absen-8d396.appspot.com',
    iosBundleId: 'com.example.absensi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjJTqaVRrxrjIuhHiFqwi4ju-i16esahE',
    appId: '1:322364170094:ios:4f748b50528d9e92c5ab7f',
    messagingSenderId: '322364170094',
    projectId: 'absen-8d396',
    databaseURL: 'https://absen-8d396-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'absen-8d396.appspot.com',
    iosBundleId: 'com.example.absensi.RunnerTests',
  );
}
